apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: user-fuse-operator-group
objects:
  - apiVersion: operators.coreos.com/v1
    kind: OperatorGroup
    metadata:
      name: ${USER_FUSE_NAMESPACE}-og
      namespace: ${USER_FUSE_NAMESPACE}
    spec:
      targetNamespaces:
      - ${USER_FUSE_NAMESPACE}
parameters:
  - description: The user fuse namespace
    name: USER_FUSE_NAMESPACE
    required: true