apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: user-fuse-subscription
objects:
  - apiVersion: operators.coreos.com/v1alpha1
    kind: Subscription
    metadata:
      name: ${USERNAME}-syndesis
      namespace: ${USER_FUSE_NAMESPACE}
    spec:
      channel: rhmi
      config:
        resources: {}
      installPlanApproval: Manual
      name: rhmi-syndesis
      source: rhmi-registry-cs
      sourceNamespace: ${USER_FUSE_NAMESPACE}
parameters:
  - description: The user's username
    name: USERNAME
    required: true
  - description: The user fuse namespace
    name: USER_FUSE_NAMESPACE
    required: true