---
- name: Delete existing KeycloakUser CRs with matching names
  shell: oc delete keycloakuser $(oc get keycloakuser -n redhat-rhmi-rhsso | awk '/{{lab_users_name_prefix}}/ {print $1}' | xargs) -n redhat-rhmi-rhsso
  register: _sso_user_del
  failed_when: _sso_user_del.rc != 0 and 'resource(s) were provided, but no name' not in _sso_user_del.stderr

- name: Delete existing OpenShift users with matching name format
  shell: oc delete user $(oc get users | awk '/{{lab_users_name_prefix}}/ {print $1}' | xargs) -n redhat-rhmi-rhsso
  register: _oc_user_del
  failed_when: _oc_user_del.rc != 0 and 'resource(s) were provided, but no name' not in _oc_user_del.stderr

- name: Delete existing realm
  shell: oc delete keycloakrealm/{{lab_sso_realm}} -n redhat-rhmi-rhsso
  register: _sso_realm_del
  failed_when: _sso_realm_del.rc != 0 and 'Error from server (NotFound)' not in _sso_realm_del.stderr

- name: Create workshop user accounts (this can take a while...)
  shell: REALM={{lab_sso_realm}} PASSWORD={{lab_user_password}} REGULAR_USERNAME={{lab_users_name_prefix}} NUM_REGULAR_USER={{lab_user_count}} sh {{repo_root}}/rhmi/setup-idp.sh
