---
- hosts: localhost
  gather_facts: yes
  tasks:
    - include_role:
        name: requirements
    - include_role:
        name: uninstall
    - include_role:
        name: threescale
      vars:
        action: uninstall

