---

- name: get master host url from route
  shell: oc get route -n {{ namespace }} --selector=zync.3scale.net/route-to=system-master -o jsonpath='{.items[0].spec.host}'
  register: _action_get_threescale_master_host

- name: get master access token from secret
  shell: oc get secret {{ seed_secret_name }} -n {{ namespace }} -o jsonpath='{.data.MASTER_ACCESS_TOKEN}'
  register: _action_get_threescale_access_token

- set_fact:
    threescale_master_host: https://{{ _action_get_threescale_master_host.stdout }}
    threescale_master_token: "{{ _action_get_threescale_access_token.stdout | b64decode }}"

- debug: msg="found 3scale master host - {{ threescale_master_host }}"

- name: create 3scale tenants
  include_tasks: create-tenant.yml
  with_sequence: count="{{ lab_user_count }}"
  when: action == "install"

- name: delete 3scale tenants
  include_tasks: delete-tenant.yml
  with_sequence: count="{{ lab_user_count }}"
  when: action == "uninstall"