apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-streams-subscription
  namespace: city-of-losangeles
spec:
  channel: stable
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
