---
- name: Delete lab project
  shell: oc delete project city-of-losangeles --ignore-not-found=true
  ignore_errors: True

- name: Delete Fuse Online instances
  shell: sh {{repo_root}}/rhmi/user-fuse-cleanup.sh
  ignore_errors: yes
