---
action: install
namespace: redhat-rhmi-3scale

seed_secret_name: system-seed

tmp_dir: /tmp

# default tenant details
tenant_name: admin-tenant
tenant_admin_user: admin
tenant_admin_email: admin@example.com
tenant_admin_password: Password1
tenant_detail_secret_name: "{{ tenant_name }}"
tenant_detail_secret_namespace: "{{ namespace }}"
tenant_id_format: evals%02d

# template references
template_credential_secret: tenant-secret.json.j2
template_tenant_resource: tenant.json.j2
